# Generated by Django 4.2.7 on 2025-11-30 08:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('timeframe', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('change', models.DecimalField(decimal_places=4, max_digits=10)),
                ('change_percent', models.DecimalField(decimal_places=4, max_digits=10)),
                ('volume', models.BigIntegerField()),
                ('avg_volume', models.BigIntegerField()),
                ('volume_ratio', models.FloatField()),
                ('is_unusual_volume', models.BooleanField(default=False)),
                ('is_breakout', models.BooleanField(default=False)),
                ('is_gainer', models.BooleanField(default=False)),
                ('is_loser', models.BooleanField(default=False)),
                ('trend', models.CharField(choices=[('Bullish', 'Bullish'), ('Bearish', 'Bearish'), ('Neutral', 'Neutral')], max_length=10)),
                ('resistance', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('support', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'market_scan_results',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('url_to_image', models.URLField(blank=True, max_length=1000, null=True)),
                ('source', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'news_articles',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ai_sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20)),
                ('ai_score', models.FloatField(help_text='Sentiment score from -1 (negative) to 1 (positive)')),
                ('analysis', models.TextField(help_text='Detailed sentiment analysis')),
                ('overall_sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20)),
                ('overall_score', models.FloatField()),
                ('confidence', models.FloatField(default=0.0, help_text='Confidence score 0-1')),
                ('bullish_count', models.IntegerField(default=0)),
                ('neutral_count', models.IntegerField(default=0)),
                ('bearish_count', models.IntegerField(default=0)),
                ('total_articles', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sentiments',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, default='USD', max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
        migrations.CreateModel(
            name='TechnicalIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('sma_20', models.FloatField(blank=True, help_text='20-day Simple Moving Average', null=True)),
                ('sma_50', models.FloatField(blank=True, help_text='50-day Simple Moving Average', null=True)),
                ('sma_200', models.FloatField(blank=True, help_text='200-day Simple Moving Average', null=True)),
                ('ema_12', models.FloatField(blank=True, help_text='12-day Exponential Moving Average', null=True)),
                ('ema_26', models.FloatField(blank=True, help_text='26-day Exponential Moving Average', null=True)),
                ('rsi_14', models.FloatField(blank=True, help_text='14-day Relative Strength Index', null=True)),
                ('macd', models.FloatField(blank=True, help_text='Moving Average Convergence Divergence', null=True)),
                ('macd_signal', models.FloatField(blank=True, help_text='MACD Signal Line', null=True)),
                ('macd_histogram', models.FloatField(blank=True, help_text='MACD Histogram', null=True)),
                ('bollinger_upper', models.FloatField(blank=True, help_text='Bollinger Bands Upper Band', null=True)),
                ('bollinger_middle', models.FloatField(blank=True, help_text='Bollinger Bands Middle Band', null=True)),
                ('bollinger_lower', models.FloatField(blank=True, help_text='Bollinger Bands Lower Band', null=True)),
                ('atr_14', models.FloatField(blank=True, help_text='14-day Average True Range', null=True)),
                ('obv', models.BigIntegerField(blank=True, help_text='On-Balance Volume', null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='market.stock')),
            ],
            options={
                'db_table': 'technical_indicators',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('high', models.DecimalField(decimal_places=4, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('low', models.DecimalField(decimal_places=4, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('close', models.DecimalField(decimal_places=4, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('volume', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('adjusted_close', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='market.stock')),
            ],
            options={
                'db_table': 'stock_prices',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('current_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('short_term_target', models.DecimalField(decimal_places=4, max_digits=12)),
                ('short_term_change', models.DecimalField(decimal_places=4, max_digits=8)),
                ('short_term_confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('short_term_trend', models.CharField(choices=[('Uptrend', 'Uptrend'), ('Downtrend', 'Downtrend'), ('Sideways', 'Sideways')], max_length=20)),
                ('medium_term_target', models.DecimalField(decimal_places=4, max_digits=12)),
                ('medium_term_change', models.DecimalField(decimal_places=4, max_digits=8)),
                ('medium_term_confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('medium_term_trend', models.CharField(choices=[('Uptrend', 'Uptrend'), ('Downtrend', 'Downtrend'), ('Sideways', 'Sideways')], max_length=20)),
                ('long_term_target', models.DecimalField(decimal_places=4, max_digits=12)),
                ('long_term_change', models.DecimalField(decimal_places=4, max_digits=8)),
                ('long_term_confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('long_term_trend', models.CharField(choices=[('Uptrend', 'Uptrend'), ('Downtrend', 'Downtrend'), ('Sideways', 'Sideways')], max_length=20)),
                ('bullish_score', models.FloatField(help_text='Bullish score 0-100')),
                ('risk_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('overall_sentiment', models.CharField(choices=[('Bullish', 'Bullish'), ('Bearish', 'Bearish'), ('Neutral', 'Neutral')], max_length=20)),
                ('model_version', models.CharField(default='1.0', max_length=50)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='market.stock')),
            ],
            options={
                'db_table': 'stock_predictions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['symbol'], name='stocks_symbol_7bc68d_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['sector'], name='stocks_sector_88fdef_idx'),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='news_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='market.newsarticle'),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiments', to='market.stock'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='market.stock'),
        ),
        migrations.AddField(
            model_name='marketscanresult',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='market.stock'),
        ),
        migrations.AddIndex(
            model_name='technicalindicator',
            index=models.Index(fields=['stock', 'timestamp'], name='technical_i_stock_i_be1620_idx'),
        ),
        migrations.AddIndex(
            model_name='technicalindicator',
            index=models.Index(fields=['timestamp'], name='technical_i_timesta_ec6aeb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='technicalindicator',
            unique_together={('stock', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['stock', 'timestamp'], name='stock_price_stock_i_d47eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['timestamp'], name='stock_price_timesta_46bf57_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockprice',
            unique_together={('stock', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='stockprediction',
            index=models.Index(fields=['stock', 'timestamp'], name='stock_predi_stock_i_b2b120_idx'),
        ),
        migrations.AddIndex(
            model_name='stockprediction',
            index=models.Index(fields=['timestamp'], name='stock_predi_timesta_c86e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='sentiment',
            index=models.Index(fields=['stock', 'timestamp'], name='sentiments_stock_i_fa4404_idx'),
        ),
        migrations.AddIndex(
            model_name='sentiment',
            index=models.Index(fields=['timestamp'], name='sentiments_timesta_b023fd_idx'),
        ),
        migrations.AddIndex(
            model_name='sentiment',
            index=models.Index(fields=['overall_sentiment'], name='sentiments_overall_662b82_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['stock', 'published_at'], name='news_articl_stock_i_97bd9e_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['published_at'], name='news_articl_publish_0977be_idx'),
        ),
        migrations.AddIndex(
            model_name='marketscanresult',
            index=models.Index(fields=['timeframe', 'timestamp'], name='market_scan_timefra_ecd9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='marketscanresult',
            index=models.Index(fields=['stock', 'timeframe'], name='market_scan_stock_i_1c047b_idx'),
        ),
        migrations.AddIndex(
            model_name='marketscanresult',
            index=models.Index(fields=['is_unusual_volume'], name='market_scan_is_unus_f040fd_idx'),
        ),
        migrations.AddIndex(
            model_name='marketscanresult',
            index=models.Index(fields=['is_breakout'], name='market_scan_is_brea_b030e2_idx'),
        ),
    ]
