MARKET_OPEN_HOUR = 9
MARKET_OPEN_MINUTE = 30
MARKET_CLOSE_HOUR = 16
MARKET_CLOSE_MINUTE = 0

# Popular stock symbols
POPULAR_STOCKS = [
    'AAPL', 'MSFT', 'GOOGL', 'AMZN', 'META', 'TSLA', 'NVDA', 'JPM',
    'JNJ', 'V', 'WMT', 'PG', 'MA', 'UNH', 'HD', 'DIS', 'BAC', 'ADBE',
    'NFLX', 'CRM', 'CSCO', 'PEP', 'KO', 'INTC', 'CMCSA', 'VZ', 'T', 'NKE'
]

# Technical indicator thresholds
RSI_OVERSOLD = 30
RSI_OVERBOUGHT = 70
RSI_NEUTRAL_LOW = 40
RSI_NEUTRAL_HIGH = 60

# Market scanner thresholds
GAINER_THRESHOLD = 0.01  # 0.01% gain (very sensitive for demo)
LOSER_THRESHOLD = -0.01  # 0.01% loss (very sensitive for demo)
UNUSUAL_VOLUME_RATIO = 1.2  # 1.2x average volume
BREAKOUT_THRESHOLD = 0.05  # 0.05% move (very sensitive for demo)

# Subscription limits
BASIC_DAILY_REQUESTS = 1000
PREMIUM_DAILY_REQUESTS = 10000
PRO_DAILY_REQUESTS = 100000

BASIC_WATCHLIST_LIMIT = 50
PREMIUM_WATCHLIST_LIMIT = 200
PRO_WATCHLIST_LIMIT = 1000

# Cache timeouts (seconds)
CACHE_TIMEOUT_SHORT = 60  # 1 minute
CACHE_TIMEOUT_MEDIUM = 300  # 5 minutes
CACHE_TIMEOUT_LONG = 3600  # 1 hour
CACHE_TIMEOUT_DAY = 86400  # 24 hours

# Celery task settings
CELERY_MAX_RETRIES = 3
CELERY_RETRY_DELAY = 60  # seconds

# ML model settings
LSTM_SEQUENCE_LENGTH = 60
LSTM_PREDICTION_DAYS = 90
ARIMA_ORDER = (5, 1, 0)

# Sentiment score ranges
SENTIMENT_VERY_NEGATIVE = -0.8
SENTIMENT_NEGATIVE = -0.2
SENTIMENT_NEUTRAL = 0.0
SENTIMENT_POSITIVE = 0.2
SENTIMENT_VERY_POSITIVE = 0.8