# Generated by Django 4.2.7 on 2025-11-30 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('alert_price_above', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('alert_price_below', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watchlist Item',
                'verbose_name_plural': 'Watchlist Items',
                'db_table': 'watchlists',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['user', 'added_at'], name='watchlists_user_id_2cb387_idx')],
                'unique_together': {('user', 'stock')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioHolding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shares', models.DecimalField(decimal_places=4, max_digits=12)),
                ('average_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('purchase_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio Holding',
                'verbose_name_plural': 'Portfolio Holdings',
                'db_table': 'portfolio_holdings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='portfolio_h_user_id_2426c1_idx'), models.Index(fields=['user', 'stock'], name='portfolio_h_user_id_0e9e5b_idx')],
                'unique_together': {('user', 'stock')},
            },
        ),
    ]
